In [1]:
# Importing Packages
import sqlite3
import pandas as pd

In [2]:
# Connecting to the Impla Server
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
print("Database created successfully!")

Database created successfully!

In [3]:
cursor.execute("""
CREATE TABLE students (
    student_id INTEGER,
    name TEXT,
    age INTEGER,
    course TEXT,
    marks REAL
)
""")
print("Table 'students' created!")

Table 'students' created!

In [4]:
students_data = [
    (1, 'Krushnali', 21, 'AI', 85.5),
    (2, 'Mayuri', 22, 'DS', 78.0),
    (3, 'Sneha', 20, 'AI', 92.3),
    (4, 'Sarthak', 21, 'ML', 88.8),
    (5, 'Sujit', 23, 'DS', 67.5)
]
cursor.executemany("INSERT INTO students VALUES (?, ?, ?, ?, ?)", students_data)
conn.commit()
print("Data inserted successfully!")

Data inserted successfully!

In [5]:
df = pd.read_sql_query("SELECT * FROM students", conn)
df

   student_id       name  age course  marks
0           1  Krushnali   21     AI   85.5
1           2     Mayuri   22     DS   78.0
2           3      Sneha   20     AI   92.3
3           4    Sarthak   21     ML   88.8
4           5      Sujit   23     DS   67.5

In [6]:
df = pd.read_sql_query("SELECT name, course FROM students", conn)
df

        name course
0  Krushnali     AI
1     Mayuri     DS
2      Sneha     AI
3    Sarthak     ML
4      Sujit     DS

In [7]:
df = pd.read_sql_query("SELECT * FROM students WHERE marks > 80", conn)
df

   student_id       name  age course  marks
0           1  Krushnali   21     AI   85.5
1           3      Sneha   20     AI   92.3
2           4    Sarthak   21     ML   88.8

In [8]:
df = pd.read_sql_query("SELECT AVG(marks) AS average_marks FROM students", conn)
df

   average_marks
0          82.42

In [9]:
cursor.execute("""
UPDATE students
SET marks = 70
WHERE student_id = 5
""")
conn.commit()
df = pd.read_sql_query("SELECT * FROM students", conn)
df

   student_id       name  age course  marks
0           1  Krushnali   21     AI   85.5
1           2     Mayuri   22     DS   78.0
2           3      Sneha   20     AI   92.3
3           4    Sarthak   21     ML   88.8
4           5      Sujit   23     DS   70.0

In [10]:
cursor.execute("DELETE FROM students WHERE student_id = 2")
conn.commit()
df = pd.read_sql_query("SELECT * FROM students", conn)
df

   student_id       name  age course  marks
0           1  Krushnali   21     AI   85.5
1           3      Sneha   20     AI   92.3
2           4    Sarthak   21     ML   88.8
3           5      Sujit   23     DS   70.0

In [11]:
cursor.execute("DROP TABLE students")
print("Table dropped successfully!")

Table dropped successfully!

In [12]:
conn.close()
print("Connection closed!")

Connection closed!